.github/workflows/build.yml, .github/workflows/deploy.yml, solutions/DummyforCICD/Other/Customizations.xml, solutions/DummyforCICD/Other/Solution.xml
Test deploy workflow on merge to branch
=> Dummyfor cicd 20220124 1310

.github/workflows/deploy.yml, solutions/DummyforCICD/Other/Customizations.xml, solutions/DummyforCICD/Other/Solution.xml
=> Dummyfor cicd 20220124 1434

.github/workflows/deploy.yml, solutions/DummyforCICD/Other/Customizations.xml, solutions/DummyforCICD/Other/Solution.xml
=> Dummyfor cicd 20220124 1518

.github/workflows/deploy.yml
Import needs to be dependent on deploy_build
=> Add needs to import

.github/workflows/build.yml, .github/workflows/deploy.yml
Separate build and deploy workflows so that exporting from build
environment as unmanaged and check in the latest solution to repository
happens on manual workflow. This will enable deployment/importing of
latest solution to other environments from the repository on push to main branch.
1) Export unmanaged solution from Build environment and create a branch for PR.
2) Import the solution from repository into Build environment and export as managed solution.
3) Managed solution as artefact is then imported into test, preprod and prod environments
https://trello.com/c/FWRhxVCa
=> Create build and deploy workflows

DqtScripts/DqtScripts/Program.cs
Add new command to clear husids where husid is not a valid husid (e.g. it's a dmsid or dttpid)
- https://trello.com/c/Y9Jeie0Z/446-filter-the-husid-column-in-dqt-so-it-contains-just-husid
=> Added clear husids command

DqtScripts/DqtScripts/Program.cs
Cleanse non husid data stored in traineeid field.
https://trello.com/c/cAGYANFZ/480-filter-the-trainee-id-field-in-dqt-so-that-it-just-contains-husids
=> Clear non husids in itt traineeid field

DqtScripts/DqtScripts/Program.cs
New script to 
- Combine Hesa Trainee Status & DMS Trainee teacher statuses. (status 210 becomes 211) 
- Backup Hesa Teacher training records.
=> Combine hesa trainee teacher & dms trainee teacher statuses

solutions/DQT20/OptionSets/dfeta_ittprogrammetype.xml
- rename provider led postgrad/undergrad.
=> rename new itt programme types

DqtScripts/DqtScripts/Program.cs
https://trello.com/c/snqMN11n/601-add-missing-he-qualification-types-to-dqt-api
- add he qualification Master of Physics (if not present)
- add he qualification Master of Chemistry (if not present)
- add he qualification  Bachelor of Arts in Combined Studies / Education of the Deaf (if not present)
=> Added new command to add he qualifications 214,215,009 if they are not present

DqtScripts/DqtScripts/Program.cs
new command added so that accounts can be updated.
https://trello.com/c/zVEi5gKd/650-bulk-update-of-itt-provider-name-la-school-code-ukprn-and-urn
=> Added new command to amend account details defined in csv file

DqtScripts/DqtScripts/Program.cs
Historically there have been more than one organsation for the same training provider. This script moves ITT records from one organisation to another from a predefined csv file.
https://trello.com/c/gvz33XF0/197-bulk-move-itt-records-onto-deduplicated-orgs
=> Move ITT records from duplicate organisations

DqtScripts/DqtScripts/DqtScripts.csproj, DqtScripts/DqtScripts/Program.cs
Added command to generate test users.
https://trello.com/c/4WxfZ2wH/284-test-data-for-gai-npq-user-testing
=> Command to generate test users

.github/workflows/import-dqt20-solution.yml, SetPluginSecureConfigTool/Program.cs, SetPluginSecureConfigTool/SetPluginSecureConfigTool.csproj, SetPluginSecureConfigTool/SetPluginSecureConfigTool.sln
Adds a console app for setting the secure config for a particular plugin type and wires up our deployment pipeline to use it for setting config for `TrnGenerationPlugin`.
=> Amend DQT20 solution deployment to set secure config for plugins

.github/workflows/import-dqt20-solution.yml
Upgrading removes deleted components whereas updating does not.
=> Upgrade solution instead of updating

DqtScripts/DqtScripts/Program.cs
Added command that reads a register file in blob storage, and replace emailaddress1 if dfeta_tspersonid is null & email address is not matching csv file email address.
https://trello.com/c/5CKTPaPB/1091-script-to-update-trainee-trns-from-a-csv
=> Added command to update email addresses

DqtScripts/DqtScripts/Program.cs
The api was incorrectly splitting firstname. This command is to fix data which is owned by the api that hasn't split the firstname into firstname/middlename(s).
=> Add command that fixes firstname/middlename

DqtScripts/DqtScripts/Program.cs
Add command that reverts the allowpiiupdatesfromregister back to a previous version that was incorrectly set in a plugin when running the command **split-first-name**.
The list of contacts that need reverting is known already, and will be uploaded to the the storage container. It will loop through the guids and retrieve the auditdetails for **contact.dfeta_allowpiiupdatesfromregister** and reverts it back to the previous version.
=> Add revert allow pii updates command

DqtScripts/DqtScripts/DateTimeExtensions.cs, DqtScripts/DqtScripts/Program.cs
Script to fix inductions that have the wrong induction start date.
=> Script to fix induction startdate to be earliest inductionperiod startdate

DqtScripts/DqtScripts/Program.cs
Adds new script backfills open trn request tasks and sets the dfeta_emailaddress attribute to the email that has been set in the description field.
https://trello.com/c/cjl8uVf9/264-prevent-a-user-from-submitting-multiple-trn-requests
=> add new script that backfills task.dfeta_emailAddress

DqtScripts/DqtScripts/Program.cs
Remove whitespaces on email address.
=> Trim whitespace on email address

DqtScripts/DqtScripts/Program.cs
new script to set slugid on itt & contact records.
https://trello.com/c/IY3Ebrzu/1039-add-missing-register-slugs-to-contact-and-itt-records
=> new script to Set itt slugid & contact slugid

DqtScripts/DqtScripts/Program.cs
Add new query to be able to export induction periods, associated teachers & appropriatebody accounts.
https://trello.com/c/CpiXHbod/473-create-a-script-to-output-induction-period-data-for-migration
=> Export inductionperiods

.github/workflows/extract-solution.yml, .github/workflows/import-dqt20-solution.yml
=> Install dotnet 7

DqtScripts/DqtScripts/Program.cs
Update induction exporter to export abs that are linked to induction periods.
=> Update exporter to join onto induction period for AB's

.github/workflows/extract-solution.yml
=> bump sdk to 9.0
